worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream auth_service {
        server auth-service:3000;
    }

    upstream catalog_service {
        server catalog-service:3000;
    }

    upstream seats_service {
        server seats-service:3000;
    }

    upstream bookings_service {
        server bookings-service:3000;
    }

    upstream payments_service {
        server payments-service:3000;
    }

    upstream otp_service {
        server otp-service:3000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass         http://auth_service/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        location /catalog/ {
            proxy_pass         http://catalog_service/catalog/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /seats/ {
            proxy_pass         http://seats_service/seats/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /bookings/ {
            proxy_pass         http://bookings_service/bookings/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /payments/ {
            proxy_pass         http://payments_service/payments/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /webhooks/ {
            proxy_pass         http://payments_service/webhooks/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /otp/ {
            proxy_pass         http://otp_service/otp/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
